from fastapi import FastAPI, Query
from fastapi.responses import JSONResponse
import os

app = FastAPI()

@app.get("/")
def read_root():
    return {"message": "Hello World!"}

@app.get("/generate")
def generate_project(country: str = Query(..., description="Country name")):
    name = country.lower().replace(" ", "-") + "-outline"
    if os.path.exists(name):
        return JSONResponse(status_code=400, content={"error": "Project already exists."})

    os.makedirs(name)

    with open(f"{name}/main.py", "w") as f:
        f.write('from fastapi import FastAPI\n\napp = FastAPI()\n\n@app.get("/")\ndef root():\n    return {"message": "Hello from ' + country + '"}\n')

    with open(f"{name}/requirements.txt", "w") as f:
        f.write("fastapi\nuvicorn\n")

    with open(f"{name}/README.md", "w") as f:
        f.write(f"# {country} Outline Project\n\nGenerated by FastAPI generator.")

    return {"status": "success", "project": name}